name: Build custom chip
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          input: vs1053b.chip.c
          output: vs1053b.chip.wasm
