name: Build custom chip
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List repo files (debug)
        run: |
          pwd
          ls -R

      - name: Build vs1053b chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          chip-json: chips/vs1053b/vs1053b.chip.json
          sources: |
            chips/vs1053b/vs1053b.chip.c
            chips/vs1053b/src/main.c
          args: -O3 -I chips/vs1053b/include

      - name: Show build outputs (debug)
        run: |
          echo "Wasms found:"
          find chips -name "*.chip.wasm" -print -exec ls -lh {} \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vs1053b-chip
          path: |
            chips/vs1053b/vs1053b.chip.json
            chips/vs1053b/vs1053b.chip.wasm
